all:
	g++ -std=c++11 -Wall -O3 -march=native lsh_del_test.cc ../../include/falconn/utils/ConcurrentBitset.cpp -o lsh_del_test -I ../../include -I ../../../external/eigen -I ../../../external/simple-serializer -pthread -lhdf5_serial
